import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OFFERS_DIR = os.path.normpath(os.path.join(BASE_DIR, "../../data/offers"))
os.makedirs(OFFERS_DIR, exist_ok=True)

def generate_offer_letter(lead_id: int, lead_name: str, priority_band: str, propensity_score: float) -> str:
    """
    Generates a PDF offer letter and returns the absolute path/file name.
    """
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    file_name = f"offer_lead_{lead_id}_{timestamp}.pdf"
    file_path = os.path.join(OFFERS_DIR, file_name)
    
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter
    
    # Draw Background Headers
    c.setFillColor(colors.HexColor("#0F172A"))
    c.rect(0, height - 100, width, 100, fill=1)
    
    # Header Text
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 55, "NEXUS BANKING GROUP")
    
    c.setFont("Helvetica", 12)
    c.drawString(40, height - 75, "Premium Client Offers Division")
    
    # Date
    c.setFillColor(colors.HexColor("#475569"))
    c.setFont("Helvetica", 11)
    c.drawString(40, height - 140, f"Date: {datetime.now().strftime('%B %d, %Y')}")
    
    # Salutation
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 16)
    display_name = lead_name if lead_name else "Valued Client"
    c.drawString(40, height - 180, f"Dear {display_name},")
    
    # Body Text
    c.setFont("Helvetica", 12)
    text = (
        "We are thrilled to inform you that following a recent review of your profile, you have "
        "been selected for an exclusive premium tier banking offer. "
        "Nexus Banking Group recognizes your strong financial standing and we "
        "believe you would benefit significantly from our tailored financing and investment solutions."
    )
    
    # Simple word wrap
    from reportlab.lib.utils import simpleSplit
    lines = simpleSplit(text, "Helvetica", 12, width - 80)
    
    y = height - 220
    for line in lines:
        c.drawString(40, y, line)
        y -= 20
        
    # Stats Box
    y -= 30
    c.setFillColor(colors.HexColor("#F8FAFC"))
    c.setStrokeColor(colors.HexColor("#E2E8F0"))
    c.rect(40, y - 80, width - 80, 80, fill=1, stroke=1)
    
    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(60, y - 30, f"Client Priority Tier: {priority_band.upper()}")
    
    c.setFont("Helvetica", 12)
    c.drawString(60, y - 55, f"Internal Profile ID: {lead_id} | Qualification Rating: {(propensity_score*100):.1f}%")
    
    # Call to action
    y -= 130
    c.setFont("Helvetica", 12)
    c.drawString(40, y, "A dedicated relationship manager will reach out within 2 business days to discuss")
    c.drawString(40, y - 20, "how we can integrate these premium rates into your banking ecosystem.")
    
    # Sign off
    y -= 60
    c.drawString(40, y, "Sincerely,")
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y - 25, "The Nexus Banking Intelligence Team")
    
    # Footer
    c.setStrokeColor(colors.HexColor("#E2E8F0"))
    c.line(40, 50, width - 40, 50)
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#94A3B8"))
    c.drawString(40, 35, "Confidential Document generated by Automated Insights Engine. Valid for 30 days.")

    c.save()
    
    return file_path
